save
transaction
exception
leaves
function
doesn
commit
created
when
request
be
db
enabled
enter_transaction_management
done
Rolls
TransactionMiddleware
Enters
that
managed
process_response
will
each
view
If
this
management
is_managed
django
process_exception
way
rollback
object
run
leave_transaction_management
response
activated
do
process_request
direct
Transaction
rolled
a
middleware
back
the
database
Commits
commit_on_response
t
an
is_dirty
successful
happens
